const express = require("express")
const app = express()
const cors = require("cors")
app.use(cors())
require("dotenv").config()
require("../../database/connection")
app.use(express.json())
app.use(express.urlencoded({extended:true}))
const userRouter = require("../../router/user.router")
app.use("/user",userRouter)
const invooRouter =require("../../router/invoo.router")
app.use("/invoice",invooRouter)
const custRouter =require("../../router/cust.router")
app.use("/cust",custRouter)
const orderRouter= require("../../router/orders.router")
app.use("/order",orderRouter)
app.get("*", (req,res)=> res.status(500).send( {error:"invalid url"} ) )
module.exports=app